// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6epS5q7dm2-SGofufQgqclLbT_u47TY4',
    appId: '1:547499044805:web:1c6342409756e27d78a5ac',
    messagingSenderId: '547499044805',
    projectId: 'notesapp-d281d',
    authDomain: 'notesapp-d281d.firebaseapp.com',
    storageBucket: 'notesapp-d281d.appspot.com',
    measurementId: 'G-5KEJNMHLY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5fcffwiMpYgRcYBqS0SvrFKI81Nvfk6U',
    appId: '1:547499044805:android:55f6e4fc00da730878a5ac',
    messagingSenderId: '547499044805',
    projectId: 'notesapp-d281d',
    storageBucket: 'notesapp-d281d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKemRgUObOoLuaX8KOOhFStqLAV6rz1w',
    appId: '1:547499044805:ios:5ac57ec6af48b97178a5ac',
    messagingSenderId: '547499044805',
    projectId: 'notesapp-d281d',
    storageBucket: 'notesapp-d281d.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKemRgUObOoLuaX8KOOhFStqLAV6rz1w',
    appId: '1:547499044805:ios:5ac57ec6af48b97178a5ac',
    messagingSenderId: '547499044805',
    projectId: 'notesapp-d281d',
    storageBucket: 'notesapp-d281d.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );
}
